# SweepstacX GitHub Actions Workflow
# Add this file to .github/workflows/sweepstacx.yml

name: Code Quality Check

on:
  pull_request:
    branches: [ main, develop ]
  push:
    branches: [ main, develop ]

jobs:
  sweepstacx:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full history for git-diff mode
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Install SweepstacX
        run: npm install -g sweepstacx
      
      - name: Run SweepstacX scan
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            # Scan only changed files in PR
            sweepstacx scan --git-diff --since origin/${{ github.base_ref }}
          else
            # Full scan on push
            sweepstacx scan
          fi
      
      - name: Generate HTML report
        if: always()
        run: sweepstacx html --output sweepstacx-report.html
      
      - name: Upload HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: sweepstacx-report
          path: sweepstacx-report.html
          retention-days: 30
      
      - name: Upload JSON report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: sweepstacx-json
          path: sweepstacx-report.json
          retention-days: 30
      
      - name: Check for critical issues
        run: |
          # Fail if there are critical issues
          ISSUE_COUNT=$(jq '.issues | length' sweepstacx-report.json)
          echo "Found $ISSUE_COUNT issues"
          
          if [ "$ISSUE_COUNT" -gt 50 ]; then
            echo "❌ Too many issues found: $ISSUE_COUNT"
            exit 1
          fi
          
          echo "✅ Code quality check passed"
      
      - name: Comment on PR
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const report = JSON.parse(fs.readFileSync('sweepstacx-report.json', 'utf8'));
            
            const body = `## 📊 SweepstacX Code Quality Report
            
            **Files Scanned:** ${report.stats.files_scanned}
            **Unused Imports:** ${report.stats.unused_imports}
            **Dead Files:** ${report.stats.dead_files}
            **Stale Dependencies:** ${report.stats.stale_dependencies}
            **Total Issues:** ${report.issues.length}
            
            [View detailed HTML report](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
            `;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body
            });
