import { readFile } from 'node:fs/promises';
import { writeJSON, writeText } from '../utils/fs.js';
import { resolve } from 'node:path';

export default async function reportCmd(opts = {}) {
  const { out = 'sweepstacx-report', json = false, md = false } = opts;

  // Read the scan report generated by scan command
  const reportPath = resolve(process.cwd(), 'sweepstacx-report.json');
  let scan;

  try {
    const content = await readFile(reportPath, 'utf8');
    scan = JSON.parse(content);
  } catch (_err) {
    throw new Error('No scan report found. Run `sweepstacx scan` first.');
  }

  // If --json flag, output JSON to stdout
  if (json) {
    process.stdout.write(JSON.stringify(scan, null, 2) + '\n');
    return;
  }

  // If --md flag, output Markdown to stdout
  if (md) {
    process.stdout.write(toMarkdown(scan) + '\n');
    return;
  }

  // Default: write both JSON and MD files
  const jsonOut = `${out}.json`;
  const mdOut   = `${out}.md`;

  await writeJSON(jsonOut, scan);
  await writeText(mdOut, toMarkdown(scan));

  console.log(`Wrote ${jsonOut}`);
  console.log(`Wrote ${mdOut}`);
}

function mdLink(path) {
  return `[${path}](${encodeURI(path)})`;
}

function toMarkdown(data) {
  const s = data.stats;
  const lines = [
    '# SweepstacX — Scan Report',
    '',
    `**Scanned at:** ${data.meta?.scanned_at || 'unknown'}`,
    `**Root:** ${data.meta?.root || '.'}`,
    ''
  ];

  if (data.warnings && data.warnings.length) {
    lines.push('## Warnings');
    for (const w of data.warnings) lines.push(`- ${w}`);
    lines.push('');
  }

  lines.push(
    '## Summary',
    `- Files scanned: **${s.files_scanned}**`,
    `- Dead files: **${s.dead_files || 0}**`,
    `- Unused imports: **${s.unused_imports}**`,
    `- Duplicate blocks: **${s.duplicate_blocks}**`,
    `- Stale dependencies: **${s.stale_dependencies || 0}**`,
    '',
    '## Issues'
  );

  // Group issues by type
  const unusedImports = data.issues.filter(i => i.type === 'unused_import');
  const deadFiles = data.issues.filter(i => i.type === 'dead_file');
  const staleDeps = data.issues.filter(i => i.type === 'stale_dependency');

  if (unusedImports.length > 0) {
    lines.push('', '### Unused Imports');
    for (const i of unusedImports) {
      lines.push(`- \`${i.symbol}\` in ${mdLink(i.file)}`);
    }
  }

  if (deadFiles.length > 0) {
    lines.push('', '### Dead Files');
    for (const i of deadFiles) {
      lines.push(`- ${mdLink(i.file)} - ${i.message}`);
    }
  }

  if (staleDeps.length > 0) {
    lines.push('', '### Stale Dependencies');
    for (const i of staleDeps) {
      lines.push(`- \`${i.name}@${i.version}\` - ${i.reason} _(${i.category})_`);
    }
  }

  if (data.issues.length === 0) {
    lines.push('', '_No issues detected. Your codebase looks clean! 🎉_');
  }

  lines.push('', '---', `_Generated by SweepstacX v${data.meta?.version || '0.3.0'}_`, '');
  return lines.join('\n');
}
